### PR TITLE
Added the possibility to show all posts sorted by categories

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
I like the idea of this. Again it might be nice to make it optional. Settings could be added to `_config.yml` to display this, or not.

Also I think the menu options `All Posts by Years` and `All Posts by Categories` are too long. Perhaps there are better alternatives.

**Comment by ghost** [comment]
I changed the design quite a bit and removed all changes I made to the menu.
I think the optionality is unnecessary now, since it's more clean and not cluttered anymore.

**Comment by jacobtomlinson** [comment]
Yeah that is much better just having a single link to all posts and then allowing the user to select a different sort. However I'm going to be a little more picky I'm afraid.
- As the posts are in sections I think "Group by" rather than "Sort by" would be more correct.
- The text underneath the title looks a little awkward and stuck on, it might be too big
- The design limits the possibility of having more grouping options (e.g tag, author, etc)

Could you possibly reduce the size of the text, remove the brackets and put the option in a dropdown box so we could have more than one other grouping option.

**Comment by ghost** [comment]
Hey! Design as requested :)

**Comment by jacobtomlinson** [comment]
Fantastic, it looks awesome!

Thanks for all your contributions. Do you have a twitter account so I can thank you more publicly?

**Comment by ghost** [comment]
Hey!

I am not using twitter, but thank you for the offer!
But seriously, I have to to thank you for this great theme... It is, in my opinion, one of the best jekyll themes out there... I really fell in love with it!

PS: Sorry for the first 'messy' pull request, where all the commits came together... I am pretty new on GitHub and did not see that coming

**Comment by jacobtomlinson** [comment]
Ok no problem!

Thanks for your kind words, I really appreciate it.

Don't worry about it, everyone makes a messy PR the first time.

**Pull request merged**
