### PR TITLE
added possibility to have custom background images

### PR DESCRIPTION
**Pull request by ghost**
I think this is pretty self-explaining :)

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Not sure about this one. The idea is interesting but I have a few issues with it.
- **Inconsistency** You can change each background and therefore make the website inconsistent.
- **Picture in git** Having images in a git repository can be a very bad thing. I have built jekyll websites with hundreds of megabytes worth of images, this can make the repo bloated and slow. I prefer to store them separately.
- **Styling** Carte Noire has a specific style. I'm happy for people to customise the theme but this may be a step too far.

**Comment by ghost** [comment]
Hey, Jacob!

I've thought about those points...
- **Inconsistency** I'd like to add a configuration option to the `_config.yml` giving three different options. First: No custom backgrounds at all (default option). Second: Only one background image which is getting displayed on all pages. Third: Full control. Ability to change the background for every page. This could lead to inconsistency, but since the user chose this option explicitly, it's okay in my opinion.
- **Picture in git** Hosting an example image on the example page seems sensible. If you were to host it elsewhere, it might get taken down without you noticing it, the link might change or the host might simply be unreachable. But I get your point, I am also going to give this an option in the `_config.yml`.
- **Styling** In my opinion this doesn't overstep the mark, since it's not drastically altering the theme. It's just a different background without changing anything else, nevertheless it's personalizing the website very much.

Cheers!

**Comment by ghost** [comment]
Done!

**Comment by ghost** [comment]
Hello, @jacobtomlinson .

It's been four days since your last response.
Is everything okay?

**Comment by jacobtomlinson** [comment]
Sorry I haven't responded. I'm just not sure that I want to include this feature in the theme. 

I feel that being able to change the background could be a drastic alteration to the theme depending on what the background is. 

It also adds another layer of complexity. If someone wants to fork the project and update the CSS to change the background image then they are free to do so. I don't think it needs to be an specific feature.

**Pull request closed without merging**
