### PR TITLE
make titles smaller if needed

### PR DESCRIPTION
**Pull request by ghost**
Hello again, Jacob!

I am addressing the following issue opened by yourself with this commit: https://github.com/jacobtomlinson/carte-noire/issues/8

Since images can say more than a thousand words, here are two pictures:

Without this commit:
bildschirmfoto vom 2016-04-04 19-22-29

With this commit:
bildschirmfoto vom 2016-04-04 19-22-45

Alternatively the js snippet could be put in the footer and therefore be available for all pages automatically without including anything explicitly. I'd prefer that personally, but since you like it to have things optional, I did it without the footer first :)

Cheers!

### CODE REVIEW

**Comment by ghost** [comment]
the js snippet is now reacting to window resizing and the main part of the snippet is just being executed when there are titles on the page

**Comment by jacobtomlinson** [comment]
This is great, thanks! I agree about including it only on pages where it is necessary. 

Why are you including jQuery again? It is already included on every page.

**Comment by ghost** [comment]
jQuery is being included in the footer and therefore not available on that position. That's why I included it again. But I have a good idea, how to make it more clean without double including anything. Going to change that.

**Comment by ghost** [comment]
Done

**Comment by jacobtomlinson** [comment]
Very nice!

**Pull request merged**
